name: ie-bank-backend

on:
  push:
    branches:
      - 'backend'
    paths:
      - 'backend/**'
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  BACKEND_WEBAPP_DEV: rmendez-be-dev
  FRONTEND_WEBAPP_UAT: rmendez-be-uat


jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'ie-bank-backend-dev'

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    
    - name: Install dependencies
      working-directory: backend 
      run: |
        pip install -r requirements.txt
    
    - name: Lint with flake8
      working-directory: backend
      run: |
        pip install flake8 pytest
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      working-directory: backend
      env:
        ENV: ${{ vars.ENV }}
        DBUSER: ${{ secrets.DBUSER }}
        DBPASS: ${{ secrets.DBPASS }}
        DBHOST: ${{ secrets.DBHOST }}
        DBNAME: ${{ secrets.DBNAME }}
      run: |
        python -m pytest --cov= . -v
    
    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v3
      with:
        name: python-app
        path: backend/

  deploy:
    if: github.event != 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: python-app
        path: .

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: List backend directory
      run: ls
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      id: deploy-to-webapp
      with:
        app-name: ${{ env.BACKEND_WEBAPP_DEV }}
        package: .

  deploy-uat:
    if: github.event_name == 'pull_request' && github.event.pull_request.base_ref == 'main' && github.event.pull_request.head_ref == 'backend' 
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: python-app
        path: .

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App UAT'
      uses: azure/webapps-deploy@v3
      id: deploy-to-webapp
      with:
        app-name: ${{ env.BACKEND_WEBAPP_UAT }}
        package: .